services:

  frontend:
    image: ghcr.io/jbonifay/ccpp-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ccpp.joffreybonifay.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.services.frontend.loadbalancer.server.scheme=http"
      - "traefik.http.services.frontend.loadbalancer.responseForwarding.flushInterval=100ms"
    networks:
      - ccpp-network

  discovery:
    image: ghcr.io/jbonifay/discovery:latest
    ports:
      - "8761:8761"
    networks:
      - ccpp-network

  api-gateway:
    image: ghcr.io/jbonifay/api-gateway:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      JWT_SECRET: ${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`ccpp.joffreybonifay.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api-gateway.entrypoints=websecure"
      - "traefik.http.routers.api-gateway.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-gateway.priority=10"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api-gateway.middlewares=api-stripprefix"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=8080"
    networks:
      - ccpp-network

  project-planning:
    image: ghcr.io/jbonifay/project-planning:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/project-planning
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - kafka
    networks:
      - ccpp-network

  workspace:
    image: ghcr.io/jbonifay/workspace:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workspace
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - kafka
    networks:
      - ccpp-network

  ideation:
    image: ghcr.io/jbonifay/ideation:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ideation
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - kafka
    networks:
      - ccpp-network

  notification:
    image: ghcr.io/jbonifay/notification:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notification
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - kafka
    networks:
      - ccpp-network

  user-management:
    image: ghcr.io/jbonifay/user-management:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user-management
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - kafka
    networks:
      - ccpp-network

  #  admin-server:
  #    image: ghcr.io/jbonifay/spring-boot-admin:latest
  #    environment:
  #      - SPRING_BOOT_ADMIN_CONTEXT_PATH=/admin
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.admin.rule=Host(`ccpp.joffreybonifay.fr`) && PathPrefix(`/admin`)"
  #      - "traefik.http.routers.admin.entrypoints=websecure"
  #      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
  #      - "traefik.http.routers.admin.priority=10"
  #      - "traefik.http.services.admin.loadbalancer.server.port=8080"
  #    networks:
  #      - ccpp-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      # KRaft mode settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # TODO: verify why
      # Listeners: one for Docker network, one for host
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      # Cluster settings
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1

      # Log settings
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - ccpp-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccpp -d ccpp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ccpp-network

networks:
  ccpp-network:
#    external: true
