services:

#  frontend:
#    image: ghcr.io/jbonifay/ccpp-frontend:latest
#    container_name: frontend
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.frontend.rule=Host(`ccpp.joffreybonifay.fr`)"
#      - "traefik.http.routers.frontend.entrypoints=websecure"
#      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.frontend.priority=1"
#      - "traefik.http.services.frontend.loadbalancer.server.port=80"
#    networks:
#      - ccpp-network

  api-gateway:
    image: ghcr.io/jbonifay/api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`ccpp.joffreybonifay.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api-gateway.entrypoints=websecure"
      - "traefik.http.routers.api-gateway.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-gateway.priority=10"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api-gateway.middlewares=api-stripprefix"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=8761"
    depends_on:
      - kafka
    networks:
      - ccpp-network

  # Microservices
  project-planning:
    image: ghcr.io/jbonifay/project-planning:latest
    container_name: project-planning
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - ccpp-network

  workspace:
    image: ghcr.io/jbonifay/workspace:latest
    container_name: workspace
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - ccpp-network

  ideation:
    image: ghcr.io/jbonifay/ideation:latest
    container_name: ideation
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - ccpp-network

  notification:
    image: ghcr.io/jbonifay/notification:latest
    container_name: notification
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - ccpp-network

#  admin-server:
#    image: ghcr.io/jbonifay/spring-boot-admin:latest
#    container_name: admin-server
#    environment:
#      - SPRING_BOOT_ADMIN_CONTEXT_PATH=/admin
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.admin.rule=Host(`ccpp.joffreybonifay.fr`) && PathPrefix(`/admin`)"
#      - "traefik.http.routers.admin.entrypoints=websecure"
#      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.admin.priority=10"
#      - "traefik.http.services.admin.loadbalancer.server.port=8080"
#    networks:
#      - ccpp-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # Listeners
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      # Cluster settings
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

      # Log settings
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - ccpp-network

networks:
  ccpp-network:
    driver: bridge
